# Generated by Django 5.2.1 on 2025-05-30 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventosMedicos', '0003_alter_cirugia_id_alter_consulta_id_and_more'),
        ('eventosMedicos', '0005_alter_cita_estado'),
    ]

    operations = [
    ]
