# Generated by Django 5.2.1 on 2025-05-30 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0003_alter_historiaclinica_id'),
        ('usuarios', '0006_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_realizacion', models.DateField()),
                ('resultados', models.TextField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_diagnosticas', to='reportes.historiaclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_diagnosticas', to='usuarios.paciente')),
            ],
        ),
    ]
